# версия файла. Подробнее https://docs.docker.com/compose/compose-file/
version: '2'

# описание сервисов проекта. При создании проекта названия контейнеров будут
# создаваться следующим образом: будет подставляться название проекта, затем
# подчеркивание, затем название контейнера.
# Название проекта берется из названия папки, в которой сейчас мы находимся.
services:
  # таким образом, если проект называется examplesite, то контейнер web будет
  # называться examplesite_web_1, где 1 - номер контейнера (в docker-compose)
  # есть возможность запустить несколько контейнеров в целях масштабирования
  web:
    image: nginx:latest # образ
    # прокидываем порт. Внимание: во время запуска проекта все остальные
    # программы, занимающие 80 порт, должны быть, конечно же, выключены
    ports:
      - 80:80
    volumes_from: # берем волумы, проброшенные с контейнера data
      - data

  # подключем контейнер data, который был собран на предыдущем шаге
  data:
    image: docker_test_project
    # в целях разработки жестко прокидываем текущую папку проекта в контейнер для того,
    # чтобы в контенерах сразу же отображались изменения, которые мы производим.
    volumes:
      - /etc/nginx
      - ./:/srv/www/app